# Generated by Django 4.2.4 on 2023-08-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excluded',
            options={'verbose_name_plural': 'Excluded Services'},
        ),
        migrations.AlterModelOptions(
            name='included',
            options={'verbose_name_plural': 'Included Services'},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AddField(
            model_name='tour',
            name='one_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='one_price_16_20',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_10_15',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_2_4',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_5_9',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='picture',
            field=models.ImageField(null=True, upload_to='tour_pictures/'),
        ),
    ]
