# Generated by Django 4.2.4 on 2023-08-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0002_alter_excluded_options_alter_included_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='price_10_15',
            new_name='price_of_10_to_15',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='one_price_16_20',
            new_name='price_of_16_to_20',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='price_2_4',
            new_name='price_of_2_to_4',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='price_5_9',
            new_name='price_of_5_to_9',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='one_price',
            new_name='price_of_one',
        ),
    ]
