# Generated by Django 4.2.4 on 2023-08-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0003_rename_price_10_15_tour_price_of_10_to_15_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
    ]
