# Generated by Django 4.2.4 on 2023-08-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0005_tour_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancellationpolicy',
            old_name='title',
            new_name='period',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='content',
        ),
        migrations.RemoveField(
            model_name='excluded',
            name='content',
        ),
        migrations.RemoveField(
            model_name='included',
            name='content',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='content',
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='percentage',
            field=models.CharField(default='25% of the actual price', max_length=255),
        ),
        migrations.AddField(
            model_name='excluded',
            name='extra_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='included',
            name='extra_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='extra_information',
            field=models.TextField(null=True),
        ),
    ]
