# Generated by Django 4.2.4 on 2023-08-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0006_rename_title_cancellationpolicy_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('num_pax', models.CharField(choices=[('1', 'Only one person'), ('2-4', 'Two to four'), ('5-9', 'Five to nine'), ('10-15', 'Ten to fiften'), ('16-20', 'Sixten to twenty')], default='1', max_length=10)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_page.tour')),
            ],
        ),
    ]
