# Generated by Django 4.2.4 on 2023-08-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0008_booking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='excluded',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='included',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
