# Generated by Django 4.2.4 on 2023-09-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0009_excluded_last_updated_included_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='price_of_one',
        ),
    ]
